// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	dynamodb "github.com/aws/aws-sdk-go/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// AttributeValueMapper is an autogenerated mock type for the AttributeValueMapper type
type AttributeValueMapper struct {
	mock.Mock
}

// MarshalMap provides a mock function with given fields: in
func (_m *AttributeValueMapper) MarshalMap(in interface{}) (map[string]*dynamodb.AttributeValue, error) {
	ret := _m.Called(in)

	var r0 map[string]*dynamodb.AttributeValue
	if rf, ok := ret.Get(0).(func(interface{}) map[string]*dynamodb.AttributeValue); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*dynamodb.AttributeValue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnmarshalMap provides a mock function with given fields: m, out
func (_m *AttributeValueMapper) UnmarshalMap(m map[string]*dynamodb.AttributeValue, out interface{}) error {
	ret := _m.Called(m, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]*dynamodb.AttributeValue, interface{}) error); ok {
		r0 = rf(m, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
