version: 2.1
orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'

    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run unit tests
          command: |
            make test-report
      - run: make build
      - store_artifacts:
          path: ./test-results
          destination: raw-test-output
      - store_test_results:
          path: ./test-reports
