// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	web "github.com/mkaiho/go-lambda-api-sample/adapter/web"
	mock "github.com/stretchr/testify/mock"
)

// CreateUserHandler is an autogenerated mock type for the CreateUserHandler type
type CreateUserHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: req
func (_m *CreateUserHandler) Handle(req web.CreateUserRequest) *web.CreateUserResponse {
	ret := _m.Called(req)

	var r0 *web.CreateUserResponse
	if rf, ok := ret.Get(0).(func(web.CreateUserRequest) *web.CreateUserResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*web.CreateUserResponse)
		}
	}

	return r0
}
