// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	web "github.com/mkaiho/go-lambda-api-sample/adapter/web"
	mock "github.com/stretchr/testify/mock"
)

// ListUsersHandler is an autogenerated mock type for the ListUsersHandler type
type ListUsersHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields:
func (_m *ListUsersHandler) Handle() *web.ListUsersResponse {
	ret := _m.Called()

	var r0 *web.ListUsersResponse
	if rf, ok := ret.Get(0).(func() *web.ListUsersResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*web.ListUsersResponse)
		}
	}

	return r0
}
