// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/mkaiho/go-lambda-api-sample/entity"
	mock "github.com/stretchr/testify/mock"
)

// DeleteUserUseCase is an autogenerated mock type for the DeleteUserUseCase type
type DeleteUserUseCase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *DeleteUserUseCase) Delete(id entity.UserID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.UserID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
