// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	util "github.com/mkaiho/go-lambda-api-sample/util"
	mock "github.com/stretchr/testify/mock"
)

// LoggerConfig is an autogenerated mock type for the LoggerConfig type
type LoggerConfig struct {
	mock.Mock
}

// Level provides a mock function with given fields:
func (_m *LoggerConfig) Level() util.LogLevel {
	ret := _m.Called()

	var r0 util.LogLevel
	if rf, ok := ret.Get(0).(func() util.LogLevel); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(util.LogLevel)
	}

	return r0
}
